namespace Solver.Solver.Cube.Enums {

    /// <summary>
    /// The basic symmetries of the cube. All other symmetries can be generated by sequences of these 4 symmetries.
    /// </summary>
    public enum BaseSym {
        RotUrf3 = 0,
        RotF2 = 1,
        RotU4 = 2,
        MirLR2 = 3,
    }
}